Update tests to use commit -m and default -u
manifest hash: 6e4385453843031a712005a320d6000595b40d05

diff --git a/tests/test-tag b/tests/test-tag
--- a/tests/test-tag
+++ b/tests/test-tag
@@ -3,11 +3,11 @@
 hg init
 echo a > a
 hg add a
-hg commit -t "test" -u test -d "0 0"
+hg commit -m "test" -d "0 0"
 hg history
-hg tag -u test -d "0 0" "bleah" 
+hg tag -d "0 0" "bleah" 
 hg history
 
 echo foo >> .hgtags
-hg tag -u test -d "0 0" "bleah2" || echo "failed" 
+hg tag -d "0 0" "bleah2" || echo "failed" 
 
