don't create the .hg/data at init time

diff --git a/tests/test-init b/tests/test-init
--- a/tests/test-init
+++ b/tests/test-init
@@ -56,6 +56,6 @@ echo "# check names for repositories (clashes with URL schemes, special chars)"
 for i in bundle file hg http https old-http ssh static-http " " "with space"; do
   echo "# hg init \"$i\""
   hg init "$i"
-  test -d "$i" -a -d "$i/.hg" -a -d "$i/.hg/data" && echo "ok" || echo "failed"
+  test -d "$i" -a -d "$i/.hg" && echo "ok" || echo "failed"
 done
 
