test-convert-darcs: skip if we can't find the elementtree module
This patch is a bit dirty to avoid having to repeat the dance required
to import elementtree.

diff --git a/tests/test-convert-darcs b/tests/test-convert-darcs
--- a/tests/test-convert-darcs
+++ b/tests/test-convert-darcs
@@ -9,6 +9,14 @@ echo 'hgext.graphlog =' >> $HGRCPATH
 DARCS_EMAIL='test@example.org'; export DARCS_EMAIL
 HOME=do_not_use_HOME_darcs; export HOME
 
+# skip if we can't import elementtree
+mkdir dummy
+mkdir dummy/_darcs
+if hg convert dummy 2>&1 | grep ElementTree > /dev/null; then
+    echo 'hghave: missing feature: elementtree module'
+    exit 80
+fi
+
 echo % initialize darcs repo
 mkdir darcs-repo
 cd darcs-repo
