tests: disable test-convert-darcs properly for darcs 2
The x bit was disabled without notice in 0018648194a9

diff --git a/tests/test-convert-darcs b/tests/test-convert-darcs
--- a/tests/test-convert-darcs
+++ b/tests/test-convert-darcs
@@ -1,6 +1,12 @@
 #!/bin/sh
 
 "$TESTDIR/hghave" darcs || exit 80
+if darcs --version 2>&1 | grep '^2\.' > /dev/null; then
+    # FIXME: darcs 2 will fail with
+    ### Abort: timeout after 180 seconds.
+    echo 'skipped: test currently disabled for darcs 2'
+    exit 80
+fi
 
 echo "[extensions]" >> $HGRCPATH
 echo "convert=" >> $HGRCPATH
