mononoke/integration: create a Makefile to run tests as part of getdeps.py build (#67)
Summary:
Pull Request resolved: https://github.com/facebookexperimental/eden/pull/67

With this change it will be possible to build dependencies of and run integration tests using getdeps.py.

Differential Revision: D24253268

fbshipit-source-id: be0ec4614959aa1e4682a1bedd891ec8245dcef9

diff --git a/eden/mononoke/tests/integration/Makefile b/eden/mononoke/tests/integration/Makefile
--- a/eden/mononoke/tests/integration/Makefile
+++ b/eden/mononoke/tests/integration/Makefile
@@ -13,12 +13,38 @@ all: help
 
 build-getdeps:
 	mkdir -p $(GETDEPS_BUILD_DIR)/mononoke_integration
-	@echo "building..."
-	touch $(GETDEPS_BUILD_DIR)/mononoke_integration/build
+	# In this step just generate the manifest.json file
+	./run_tests_getdeps.py getdeps $(GETDEPS_INSTALL_DIR) --generate_manifest
 
 install-getdeps:
 	mkdir -p $(GETDEPS_INSTALL_DIR)/mononoke_integration
-	@echo "installing..."
-	touch $(GETDEPS_BUILD_DIR)/mononoke_integration/install
+	# In this step copy the integration/ folder and the manifest.json file
+	# to the installation directory
+	cp -r ../ $(GETDEPS_INSTALL_DIR)/mononoke_integration
+	cp $(GETDEPS_BUILD_DIR)/mononoke_integration/manifest.json $(GETDEPS_INSTALL_DIR)/mononoke_integration
 
-.PHONY: help all build-getdeps install-getdeps
+test-getdeps:
+	# Custom tmp folder inside getdeps scratch path, just to make sure it
+	# has all proper permissions
+	mkdir -p $(GETDEPS_BUILD_DIR)/mononoke_integration/tests-tmp
+	# Remove the .testfailed and .testerrored files so that after this next
+	# step they are written clean
+	rm -f $(GETDEPS_INSTALL_DIR)/mononoke/source/eden/mononoke/tests/integration/.test*
+	# Unsetting http_proxy and https_proxy, because all the traffic from
+	# tests go to localhost (and for some reason the no_proxy=localhost env
+	# variable is not respected).
+	unset http_proxy; \
+	  unset https_proxy; \
+	  export TMPDIR=$(GETDEPS_BUILD_DIR)/mononoke_integration/tests-tmp; \
+	  export GETDEPS_BUILD=1; \
+	  ./run_tests_getdeps.py getdeps $(GETDEPS_INSTALL_DIR) || true
+	# Rerunnig the failed test again, because with so many tests run
+	# concurrently there is a certain amount of flakiness involved.
+	cat $(GETDEPS_INSTALL_DIR)/mononoke/source/eden/mononoke/tests/integration/.test* || true
+	unset http_proxy; \
+	  unset https_proxy; \
+	  export TMPDIR=$(GETDEPS_BUILD_DIR)/mononoke_integration/tests-tmp; \
+	  export GETDEPS_BUILD=1; \
+	  ./run_tests_getdeps.py getdeps $(GETDEPS_INSTALL_DIR) --rerun-failed
+
+.PHONY: help all build-getdeps install-getdeps test-getdeps
